
(straight-use-package 'use-package)
(straight-use-package 'popup)
(straight-use-package 'async)
(straight-use-package 'helm)
(straight-use-package 'powerline)
;;(straight-use-package 'proceed)
(straight-use-package 'spinner)
(straight-use-package 'helm-ag)
(straight-use-package 'which-key)
(straight-use-package 'rainbow-delimiters)
(straight-use-package 'markdown-mode)
(straight-use-package 'undo-tree)
(straight-use-package 'winum)
(straight-use-package 'helm-swoop)
(straight-use-package 'swoop)
(straight-use-package 'solarized-theme)
(straight-use-package 'flycheck)
(straight-use-package '(company :config (setq lsp-completion-provider :capf)))
(straight-use-package 'helm-projectile)
(straight-use-package 'projectile)
(straight-use-package 'multiple-cursors)

(provide 'my-packages)
;;; my-packages.el ends here
